import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import Link from '@mui/material/Link';
import { useRouter } from 'next/router';

const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL as string;

export default function User() {
  const router = useRouter();
  const { id } = router.query;

  return (
    <>
      <Head>
        <title>{id} - Users</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>Your ID is {id}</div>
        <div>
          <div className={styles.grid}>Route: {router.route}</div>
          <div className={styles.grid}>Pathname:{router.pathname}</div>
          <div className={styles.grid}>asPath: {router.asPath}</div>
          <div className={styles.grid}>
            Query: {JSON.stringify(router.query)}
          </div>
        </div>
        <div className={styles.grid}>
          <Link href='/'>TOP</Link>
        </div>
      </main>
    </>
  );
}
